---
title: "Gov 50 Final Project"
author: "Violet Barron"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the vast disparities between various Asian American and Native Hawaiian/Pacific Islander (AANHPI) ethnic subgroups in the United States. I plan to use publicly available U.S. census data (found at data.census.gov) to explore a multitude of variables, such as educational attainment, median household income, poverty rates, English proficiency, citizenship and immigration status, and so on. Through this project, I hope to disprove the reductionist view of the AANHPI community as a wealthy and well-educated monolith.

## Data source

How do different Asian American and Native Hawaiian/Pacific Islander (AANHPI) ethnic groups fare in America when their experiences are measured against national averages? In this study, I plan to explore the discrepancy in experiences - using a variety of metrics - across members of different AANHPI ethnic groups and compare this discrepancy with the experience of the average American citizen. I hypothesize that because the label "AANHPI" encompasses such a diverse group of ethnicities, the aggregate AANHPI experience will not be much different when compared with the national average when observing most metrics. However, when observing certain metrics, such as English proficiency, I hypothesize that AANHPI groups will fare decidedly worse than the average American. My sample is comprised of U.S. census data from 2010-2020. My unit of analysis is a specific AANHPI ethnic group (e.g. Chinese, Filipino, Burmese, etc.). The explanatory variable of interest is whether each of these ethnic groups fare better or worse than the national average across a variety of metrics (e.g. educational attainment, median household income, poverty and employment rate, English proficiency, etc.). The variable is coded =1 for better than the national average and =0 for worse than the national average. The variable is measured from publicly available U.S. data (found at data.census.gov). If I observe that across ethnic groups, AANHPI fare about equal to the average American citizen, this would provide support for my hypothesis. If, on the other hand, I observe that across ethnic groups, AANHPI fare either overwhelmingly better or worse than the average American citizen, this would provide evidence against my hypothesis. When I run my regression of the AANHPI experience against the national average, a positive, relatively insignificant coefficient would indicate support for my hypothesis.